name: Define Python version and install dependencies
inputs:
  python.version:
    required: true
    description: Version range or exact version of a Python version to use, using semver's version range syntax. [More information](https://go.microsoft.com/fwlink/?LinkID=2006180)
runs:
  using: composite
  steps:
  - name: Use Python ${{ inputs.python.version }}
    uses: actions/setup-python@v4.7.0
    with:
      python-version: "${{ inputs.python.version }}"
      architecture: x64
  - name: Install dependencies
    run: python -m pip install --upgrade pip && pip install -r requirements.txt
    shell: bash